import type { BossDefinition } from "../types/combat";
import { TEXTURE_KEYS } from "../utils/constants";

export const BOSS_DEFINITIONS = {
  bulwarkHowitzer: {
    id: "bulwarkHowitzer",
    name: "Bulwark Howitzer",
    textureKey: TEXTURE_KEYS.bossBulwark,
    color: 0xffa56b,
    width: 178,
    height: 96,
    baseHealth: 135,
    contactDamage: 40,
    enterSpeed: 92,
    targetY: 88,
    moveSpeed: 128,
    score: 2200,
    phaseThresholds: [0.7, 0.35],
    repeatHealthMultiplier: 1.15,
    repeatMoveMultiplier: 1.08,
    repeatCooldownMultiplier: 0.9
  },
  blinkReaver: {
    id: "blinkReaver",
    name: "Blink Reaver",
    textureKey: TEXTURE_KEYS.bossBlink,
    color: 0x6ef2ff,
    width: 164,
    height: 90,
    baseHealth: 150,
    contactDamage: 38,
    enterSpeed: 106,
    targetY: 92,
    moveSpeed: 148,
    score: 2350,
    phaseThresholds: [0.7, 0.35],
    repeatHealthMultiplier: 1.15,
    repeatMoveMultiplier: 1.08,
    repeatCooldownMultiplier: 0.9
  },
  broodCarrier: {
    id: "broodCarrier",
    name: "Brood Carrier",
    textureKey: TEXTURE_KEYS.bossCarrier,
    color: 0x79f7c1,
    width: 192,
    height: 108,
    baseHealth: 175,
    contactDamage: 44,
    enterSpeed: 88,
    targetY: 86,
    moveSpeed: 112,
    score: 2550,
    phaseThresholds: [0.7, 0.35],
    repeatHealthMultiplier: 1.15,
    repeatMoveMultiplier: 1.08,
    repeatCooldownMultiplier: 0.9
  },
  prismBeamArray: {
    id: "prismBeamArray",
    name: "Prism Beam Array",
    textureKey: TEXTURE_KEYS.bossPrism,
    color: 0xc39bff,
    width: 182,
    height: 102,
    baseHealth: 190,
    contactDamage: 42,
    enterSpeed: 82,
    targetY: 84,
    moveSpeed: 118,
    score: 2750,
    phaseThresholds: [0.7, 0.35],
    repeatHealthMultiplier: 1.15,
    repeatMoveMultiplier: 1.08,
    repeatCooldownMultiplier: 0.9
  },
  aegisCoreMatrix: {
    id: "aegisCoreMatrix",
    name: "Aegis Core Matrix",
    textureKey: TEXTURE_KEYS.bossAegis,
    color: 0xffd76c,
    width: 188,
    height: 106,
    baseHealth: 210,
    contactDamage: 45,
    enterSpeed: 80,
    targetY: 82,
    moveSpeed: 116,
    score: 3000,
    phaseThresholds: [0.7, 0.35],
    repeatHealthMultiplier: 1.15,
    repeatMoveMultiplier: 1.08,
    repeatCooldownMultiplier: 0.9
  }
} as const satisfies Record<string, BossDefinition>;
